# Generated by Django 2.0.5 on 2018-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='enum_type',
            field=models.IntegerField(default=0),
        ),
    ]
