# Generated by Django 2.0.5 on 2018-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20180528_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
