# Generated by Django 2.0.5 on 2018-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
