# Generated by Django 2.0.5 on 2018-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20180528_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
