# Generated by Django 2.0.5 on 2018-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20180528_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='url_img',
            field=models.URLField(blank=True),
        ),
    ]
